import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")

MAX_FILE_SIZE_MB = 20
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024

MAX_IMAGES_PER_USER = 50
MAX_PDFS_IN_MERGE = 10

PAGES_AS_IMAGES_LIMIT = 20
PDF_RENDER_DPI = 150

TELEGRAM_MAX_UPLOAD_MB = 50
